---
version: "3.8"

services:

  master:
    container_name: master
    image: ghcr.io/munenick/multipaper-master:1.20
    ports:
      - 25565:25565
    volumes:
      - master-data:/app
    environment:
      - MASTER_PORT=35353
      - PROXY_PORT=25565
      - JAVA_OPTS=-Xmx512M
  
  node1:
    image: ghcr.io/munenick/multipaper:1.20
    environment:
      - EULA=true
      - JAVA_OPTS=-Xmx1G
      - MULTIPAPER_MASTER_ADDRESS=master:35353
      - BUNGEECORD_NAME=node1
      - PROP_VIEW_DISTANCE=16
      - SPIGOT_SETTINGS_BUNGEECORD=true
      - NOGUI=true

  node2:
    image: ghcr.io/munenick/multipaper:1.20
    environment:
      - EULA=true
      - JAVA_OPTS=-Xmx1G
      - MULTIPAPER_MASTER_ADDRESS=master:35353
      - BUNGEECORD_NAME=node2
      - PROP_VIEW_DISTANCE=16
      - SPIGOT_SETTINGS_BUNGEECORD=true
      - NOGUI=true

volumes:
  master-data: