---
version: "3.8"

services:

  master:
    container_name: master
    image: ghcr.io/munenick/multipaper-master:1.20
    ports:
      - 25565:25565
    volumes:
      - master-data:/app
    environment:
      - MASTER_PORT=35353     # マスターサーバーデータベースポート
      - PROXY_PORT=25565      # プロキシポート
      - JAVA_OPTS=-Xmx512M    # マスターサーバー用のJavaオプション
  
  node1:
    image: ghcr.io/munenick/multipaper:1.20
    environment:
      - EULA=true                             # Minecraft EULAの自動承認
      - JAVA_OPTS=-Xmx1G                      # ノード用のJavaオプション
      - MULTIPAPER_MASTER_ADDRESS=master:35353 # マスターサーバーのアドレス
      - BUNGEECORD_NAME=node1                 # BungeeCord識別名
      - PROP_VIEW_DISTANCE=16                 # server.propertiesのview-distance設定
      - SPIGOT_SETTINGS_BUNGEECORD=true       # spigot.ymlのbungeecord設定
      - NOGUI=true                            # GUIを無効化

  node2:
    image: ghcr.io/munenick/multipaper:1.20
    environment:
      - EULA=true                             # Minecraft EULAの自動承認
      - JAVA_OPTS=-Xmx1G                      # ノード用のJavaオプション
      - MULTIPAPER_MASTER_ADDRESS=master:35353 # マスターサーバーのアドレス
      - BUNGEECORD_NAME=node2                 # BungeeCord識別名
      - PROP_VIEW_DISTANCE=16                 # server.propertiesのview-distance設定
      - SPIGOT_SETTINGS_BUNGEECORD=true       # spigot.ymlのbungeecord設定
      - NOGUI=true                            # GUIを無効化

# 名前付きボリュームを定義
volumes:
  master-data:
    # このボリュームはDockerが管理し、適切な権限が設定される