name: Build from Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      master_tags:
        required: true
        type: string
      server_tags:
        required: true
        type: string

jobs:
  build_release:
    name: Build image from release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: amd64,arm64,arm

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Resolve version & get URLs
        id: get_release
        run: |
          set -eux

          VERSION_INPUT="${{ inputs.version }}"
          # Determine full version (e.g., 1.20 -> 1.20.x)
          if [[ "$VERSION_INPUT" =~ ^[0-9]+\.[0-9]+$ ]]; then
            FULL_VERSION=$(curl -sSL \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/MultiPaper/MultiPaper/tags" \
              | jq -r --arg prefix "$VERSION_INPUT" \
                   '[.[] | select(.name | startswith($prefix + ".")) | .name] \
                    | sort_by(split(".")|map(tonumber)) \
                    | last')
          else
            FULL_VERSION="$VERSION_INPUT"
          fi
          echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_OUTPUT

          # Fetch version details
          RAW=$(curl -sSL -H "Accept: application/json" \
                "https://api.multipaper.io/v2/projects/multipaper/versions/$FULL_VERSION")
          BUILD=$(echo "$RAW" | jq -r '.build')
          APP_NAME=$(echo "$RAW" | jq -r '.downloads.application.name')
          MASTER_NAME=$(echo "$RAW" | jq -r '.downloads.master.name')

          # Set output variables
          echo "MULTIPAPER_URL=https://api.multipaper.io/v2/projects/multipaper/versions/$FULL_VERSION/builds/$BUILD/downloads/$APP_NAME" >> $GITHUB_OUTPUT
          echo "MULTIPAPER_MASTER_URL=https://api.multipaper.io/v2/projects/multipaper/versions/$FULL_VERSION/builds/$BUILD/downloads/$MASTER_NAME" >> $GITHUB_OUTPUT

      - name: Build base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: releases/Dockerfile
          push: false
          load: false
          target: base
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: |
            type=gha,scope=release-base
          cache-to: |
            type=gha,scope=release-base,mode=max

      - name: Build multipaper-master ${{ inputs.version }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: releases/Dockerfile
          push: true
          tags: ${{ inputs.master_tags }}
          target: master
          build-args: |
            RELEASE_URL=${{ steps.get_release.outputs.MULTIPAPER_MASTER_URL }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: |
            type=gha,scope=release-master-${{ inputs.version }}
            type=gha,scope=release-base
          cache-to: |
            type=gha,scope=release-master-${{ inputs.version }},mode=max

      - name: Build multipaper ${{ inputs.version }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: releases/Dockerfile
          push: true
          tags: ${{ inputs.server_tags }}
          target: server
          build-args: |
            RELEASE_URL=${{ steps.get_release.outputs.MULTIPAPER_URL }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: |
            type=gha,scope=release-server-${{ inputs.version }}
            type=gha,scope=release-base
          cache-to: |
            type=gha,scope=release-server-${{ inputs.version }},mode=max
